import type { Metadata } from "next";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "DaizyAI Ltd Terms & Conditions — the agreement governing our AI voice agent services. Governed by the laws of England and Wales.",
};

export default function TermsPage() {
  return (
    <main>
      <section className="legal-hero">
        <div className="container">
          <p className="legal-eyebrow">DaizyAI</p>
          <h1 className="legal-title">Terms &amp; Conditions</h1>
          <div className="legal-meta">
            <span>Effective date: 1 May 2026</span>
            <span>Last reviewed: 1 May 2026</span>
            <span>Version 1.0</span>
          </div>
        </div>
      </section>

      <section className="legal-body">
        <div className="container legal-container">

          {/* Intro callout */}
          <div className="legal-callout">
            These Terms &amp; Conditions (&quot;Terms&quot;) govern the agreement between <strong>DaizyAI Ltd</strong> (&quot;DaizyAI&quot;, &quot;we&quot;, &quot;us&quot;) and the business or individual (&quot;Client&quot;, &quot;you&quot;) accessing or using DaizyAI&apos;s services. By signing an Order Form, paying a subscription fee, or using the service, you agree to these Terms in full.
          </div>

          {/* Table of Contents */}
          <nav className="legal-toc">
            <p className="legal-toc-title">Contents</p>
            <ol className="legal-toc-list">
              <li><a href="#t1">Definitions &amp; Interpretation</a></li>
              <li><a href="#t2">The Services</a></li>
              <li><a href="#t3">Onboarding &amp; Setup</a></li>
              <li><a href="#t4">Subscription &amp; Pricing</a></li>
              <li><a href="#t5">Payment Terms</a></li>
              <li><a href="#t6">Call Recordings &amp; Data</a></li>
              <li><a href="#t7">Template Reuse</a></li>
              <li><a href="#t8">Client Obligations</a></li>
              <li><a href="#t9">Acceptable Use</a></li>
              <li><a href="#t10">Intellectual Property</a></li>
              <li><a href="#t11">Confidentiality</a></li>
              <li><a href="#t12">Liability &amp; Warranties</a></li>
              <li><a href="#t13">Term &amp; Termination</a></li>
              <li><a href="#t14">Data Protection</a></li>
              <li><a href="#t15">General</a></li>
            </ol>
          </nav>

          {/* 01 */}
          <div className="legal-section" id="t1">
            <p className="legal-section-num">01</p>
            <h2>Definitions &amp; Interpretation</h2>
            <table className="legal-table">
              <thead><tr><th>Term</th><th>Meaning</th></tr></thead>
              <tbody>
                <tr><td><strong>Agreement</strong></td><td>These Terms together with any Order Form or SOW signed by the Client.</td></tr>
                <tr><td><strong>Agent</strong></td><td>The AI voice agent configured and deployed by DaizyAI for the Client under the Agreement.</td></tr>
                <tr><td><strong>Call Recording</strong></td><td>An audio recording and/or transcript of a call handled by the Agent, stored on Retell AI infrastructure.</td></tr>
                <tr><td><strong>Caller / End-Customer</strong></td><td>A third party who calls a phone number operated by the Agent on the Client&apos;s behalf.</td></tr>
                <tr><td><strong>Confidential Information</strong></td><td>Any non-public information disclosed by one party to the other in connection with the Agreement.</td></tr>
                <tr><td><strong>DPA</strong></td><td>Data Processing Agreement — the separate document governing DaizyAI&apos;s processing of personal data on the Client&apos;s behalf.</td></tr>
                <tr><td><strong>Lead Summary</strong></td><td>A structured output generated by the Agent following a call, delivered to the Client&apos;s nominated destination.</td></tr>
                <tr><td><strong>Order Form</strong></td><td>A written or electronic document specifying the Services, pricing, and subscription tier agreed with the Client.</td></tr>
                <tr><td><strong>Services</strong></td><td>The AI voice agent configuration, deployment, maintenance, reporting, and optional Meta Ads management services provided by DaizyAI.</td></tr>
                <tr><td><strong>Vertical Template</strong></td><td>A reusable, anonymised configuration framework used to accelerate agent deployment within a business sector.</td></tr>
              </tbody>
            </table>
            <p>References to &quot;including&quot; mean &quot;including without limitation&quot;. Headings are for convenience only.</p>
          </div>

          {/* 02 */}
          <div className="legal-section" id="t2">
            <p className="legal-section-num">02</p>
            <h2>The Services</h2>

            <h3>Core Services</h3>
            <p>DaizyAI will, subject to payment of the applicable fees, provide the following to the Client:</p>
            <ul>
              <li>Configuration and deployment of an AI voice agent to handle inbound calls on the Client&apos;s behalf</li>
              <li>A five-layer inbound communication stack: call capture, qualification, decision logic, lead delivery, and reporting</li>
              <li>A dedicated phone number assigned to the Agent</li>
              <li>Access to a reporting dashboard showing call volumes, lead quality, recordings, and transcripts</li>
              <li>Monthly optimisation review of the Agent based on call recordings and performance data</li>
            </ul>

            <h3>Optional Services</h3>
            <p>Where agreed separately in an Order Form, DaizyAI may also provide:</p>
            <ul>
              <li>Managed Meta Ads services — campaign creation, targeting, and optimisation. Ad spend is paid directly by the Client to Meta.</li>
              <li>Additional Agent workflows (multi-language, multi-location, additional phone numbers)</li>
              <li>Custom CRM integrations beyond our standard integration library</li>
            </ul>

            <h3>Service Availability</h3>
            <p>DaizyAI targets 99% uptime for Agent availability, excluding scheduled maintenance and events outside our reasonable control. We do not provide a financially guaranteed SLA unless explicitly stated in an Order Form.</p>

            <h3>Service Changes</h3>
            <p>We may update, modify, or improve the Services from time to time. Where a change materially reduces the Services, we will give 30 days&apos; notice.</p>
          </div>

          {/* 03 */}
          <div className="legal-section" id="t3">
            <p className="legal-section-num">03</p>
            <h2>Onboarding &amp; Setup</h2>

            <h3>Onboarding Process</h3>
            <p>DaizyAI&apos;s standard onboarding process involves six steps: discovery call, template selection, configuration, test cycle, go-live, and initial optimisation.</p>

            <h3>Onboarding Fee</h3>
            <p>A one-time onboarding fee applies per deployment as stated in the Order Form or published pricing. It is non-refundable once the go-live step has been completed.</p>

            <h3>Client Responsibilities During Onboarding</h3>
            <ul>
              <li>Provide accurate and complete information requested during the discovery process</li>
              <li>Make a representative available to test the Agent before go-live</li>
              <li>Provide access credentials or webhook details for nominated integration destinations</li>
              <li>Review and approve Agent scripts before go-live</li>
            </ul>
            <p>DaizyAI is not responsible for poor Agent performance resulting from inaccurate or incomplete information provided by the Client during onboarding.</p>

            <h3>Go-Live Timeline</h3>
            <p>We target a go-live within 7 business days of receiving all required information from the Client.</p>
          </div>

          {/* 04 */}
          <div className="legal-section" id="t4">
            <p className="legal-section-num">04</p>
            <h2>Subscription &amp; Pricing</h2>

            <h3>Subscription Tiers</h3>
            <table className="legal-table">
              <thead><tr><th>Tier</th><th>Monthly Fee</th><th>Included Minutes</th><th>Notes</th></tr></thead>
              <tbody>
                <tr><td><strong>Pilot</strong></td><td>£99 one-time</td><td>100 minutes</td><td>Non-recurring trial. Onboarding: £50.</td></tr>
                <tr><td><strong>Starter</strong></td><td>£299/month</td><td>300 minutes</td><td>Onboarding: £200 (one-time).</td></tr>
                <tr><td><strong>Growth</strong></td><td>£599/month</td><td>1,000 minutes</td><td>Most popular. Onboarding: £400 (one-time).</td></tr>
                <tr><td><strong>Scale</strong></td><td>£999/month</td><td>Multiple workflows</td><td>Custom minutes. Onboarding: £800 (one-time).</td></tr>
              </tbody>
            </table>
            <p>Pricing is as published on daizyai.uk at the time of order, or as stated in a signed Order Form. Existing subscribers will receive 30 days&apos; notice before a price increase takes effect.</p>

            <h3>Minute Overage</h3>
            <p>If the Client&apos;s Agent exceeds the included monthly minutes, overage is charged at the rate stated in the Order Form or, if not stated, at DaizyAI&apos;s then-current overage rate.</p>

            <h3>Meta Ads Management Fees</h3>
            <p>Where Meta Ads management is engaged, DaizyAI&apos;s fee is a tiered management fee charged in addition to the subscription fee. Ad spend is paid directly by the Client to Meta.</p>
          </div>

          {/* 05 */}
          <div className="legal-section" id="t5">
            <p className="legal-section-num">05</p>
            <h2>Payment Terms</h2>

            <h3>Invoicing</h3>
            <p>Subscription fees are invoiced monthly in advance. Onboarding fees are invoiced at the time of order. Meta Ads management fees are invoiced monthly in arrears.</p>

            <h3>Payment</h3>
            <p>Invoices are due within <strong>14 days</strong> of the invoice date. All fees are stated exclusive of VAT; VAT at the prevailing rate will be added where applicable.</p>

            <h3>Late Payment</h3>
            <p>Invoices unpaid after 14 days may attract statutory interest at 8% above the Bank of England base rate. DaizyAI reserves the right to suspend the Service with 7 days&apos; written notice if an invoice remains unpaid after 30 days.</p>

            <h3>Disputes</h3>
            <p>If the Client disputes an invoice in good faith, they must notify DaizyAI within 7 days of the invoice date. Undisputed portions remain payable on the normal due date.</p>
          </div>

          {/* 06 */}
          <div className="legal-section" id="t6">
            <p className="legal-section-num">06</p>
            <h2>Call Recordings &amp; Data</h2>

            <h3>Recording of Calls</h3>
            <p>All calls handled by the Agent are recorded and transcribed by default as part of the Service. Call recordings and transcripts are stored on infrastructure operated by <strong>Retell AI, Inc.</strong></p>

            <div className="legal-callout legal-callout--warn">
              <strong>Client&apos;s obligation:</strong> The Client is responsible as Data Controller for ensuring that their end-customers are appropriately informed that calls may be recorded and may be handled by an AI system.
            </div>

            <h3>Access to Recordings</h3>
            <p>The Client may access their call recordings via the DaizyAI reporting dashboard for the duration of the retention period. No other party is permitted to access recordings without consent or a legal obligation.</p>

            <h3>Retention</h3>
            <p>Call recordings and transcripts are retained for a default period of <strong>12 months</strong> from the call date. On termination, all caller data will be deleted within 30 days.</p>

            <h3>Deletion Requests</h3>
            <p>Deletion requests must be submitted in writing to <a href="mailto:daizyaiinfo@gmail.com">daizyaiinfo@gmail.com</a>. We will action deletion within 14 days of a verified request.</p>

            <h3>Client Responsibility for Caller Data</h3>
            <p>The Client is the Data Controller for personal data relating to their callers. DaizyAI acts as Data Processor. The Client&apos;s obligations are set out in the DPA, which forms part of this Agreement.</p>
          </div>

          {/* 07 */}
          <div className="legal-section" id="t7">
            <p className="legal-section-num">07</p>
            <h2>Template Reuse &amp; Intellectual Property in Agents</h2>

            <h3>Vertical Templates</h3>
            <p>DaizyAI builds and maintains a library of Vertical Templates — anonymised, generalised configuration frameworks for each sector we serve.</p>

            <div className="legal-callout">
              <strong>What we use and what we do not:</strong> Vertical Templates contain only generalised, anonymised configuration logic. They never contain the Client&apos;s business name, branding, or any personal data relating to the Client&apos;s callers.
            </div>

            <h3>Specifically, DaizyAI will never incorporate into any Vertical Template:</h3>
            <ul>
              <li>The Client&apos;s business name, trading name, or branding</li>
              <li>The names, phone numbers, or any other personal data of the Client&apos;s callers</li>
              <li>Call recordings (audio or transcript) attributable to the Client</li>
              <li>CRM credentials, integration configurations, or webhook data</li>
              <li>Commercially sensitive information specific to the Client&apos;s business</li>
            </ul>

            <h3>Ownership of the Agent</h3>
            <p>The Client does not own the Agent or the underlying AI models. DaizyAI grants the Client a limited, non-exclusive, non-transferable licence to use the Agent for the duration of the Agreement.</p>

            <h3>AI Model Training</h3>
            <p>DaizyAI does not use the Client&apos;s call recordings, transcripts, or caller data to train or fine-tune any AI model.</p>
          </div>

          {/* 08 */}
          <div className="legal-section" id="t8">
            <p className="legal-section-num">08</p>
            <h2>Client Obligations</h2>
            <p>The Client agrees to:</p>
            <ul>
              <li>Provide accurate, complete, and up-to-date information during onboarding and throughout the Agreement</li>
              <li>Ensure that their use of the Service complies with all applicable laws, including UK GDPR and the Data Protection Act 2018</li>
              <li>Maintain a lawful basis under UK GDPR for processing personal data relating to callers through the Service</li>
              <li>Ensure their own privacy notice accurately describes AI voice agents and call recording</li>
              <li>Not share login credentials or dashboard access with unauthorised third parties</li>
              <li>Notify DaizyAI promptly of any change to their business that materially affects how the Agent should operate</li>
              <li>Pay all invoices by the due date</li>
              <li>Not misrepresent DaizyAI, its Services, or its Agents to callers or third parties</li>
            </ul>
          </div>

          {/* 09 */}
          <div className="legal-section" id="t9">
            <p className="legal-section-num">09</p>
            <h2>Acceptable Use</h2>

            <div className="legal-callout legal-callout--important">
              Breach of this section may result in immediate suspension of the Service without refund.
            </div>

            <p>The Client must not use the Service:</p>
            <ul>
              <li>To make or facilitate outbound marketing calls without the appropriate consent and PECR compliance framework</li>
              <li>To deceive callers who sincerely ask whether they are speaking to a human or AI</li>
              <li>For any unlawful purpose, including fraud, harassment, or any activity that violates applicable law</li>
              <li>To process special category personal data without first notifying DaizyAI and obtaining written approval</li>
              <li>In any way that infringes third-party intellectual property rights</li>
              <li>To attempt to reverse-engineer, copy, or replicate DaizyAI&apos;s Vertical Templates or proprietary systems</li>
              <li>In any sector requiring a regulated licence without ensuring appropriate human oversight</li>
            </ul>
          </div>

          {/* 10 */}
          <div className="legal-section" id="t10">
            <p className="legal-section-num">10</p>
            <h2>Intellectual Property</h2>

            <h3>DaizyAI&apos;s IP</h3>
            <p>All intellectual property rights in the Services, including Vertical Templates, configuration frameworks, qualification scripts, and DaizyAI&apos;s brand, are owned by DaizyAI or its licensors.</p>

            <h3>Client&apos;s IP</h3>
            <p>All intellectual property rights in the Client&apos;s business name, branding, and business-specific data remain owned by the Client. The Client grants DaizyAI a limited licence to use such information solely for operating the Agent.</p>

            <h3>Feedback</h3>
            <p>If the Client provides feedback or suggestions regarding the Services, DaizyAI may use such feedback without restriction or compensation.</p>
          </div>

          {/* 11 */}
          <div className="legal-section" id="t11">
            <p className="legal-section-num">11</p>
            <h2>Confidentiality</h2>
            <p>Each party agrees to keep the other&apos;s Confidential Information confidential, except:</p>
            <ul>
              <li>To employees, contractors, or sub-processors who need to know it</li>
              <li>As required by law, court order, or regulatory authority</li>
              <li>If the information enters the public domain other than through a breach</li>
            </ul>
            <p>This confidentiality obligation survives termination for a period of <strong>3 years</strong>.</p>
          </div>

          {/* 12 */}
          <div className="legal-section" id="t12">
            <p className="legal-section-num">12</p>
            <h2>Liability &amp; Warranties</h2>

            <h3>DaizyAI&apos;s Warranties</h3>
            <p>DaizyAI warrants that it has the right and authority to enter into this Agreement, will perform the Services with reasonable skill and care, and will process personal data in accordance with the DPA and applicable data protection law.</p>

            <h3>No Guarantee of Results</h3>
            <p>DaizyAI does not warrant any specific business outcome, including lead volumes, conversion rates, or revenue uplift.</p>

            <h3>Exclusion of Consequential Loss</h3>
            <p>To the maximum extent permitted by law, DaizyAI shall not be liable for loss of profits, revenue, business, anticipated savings, goodwill, or any indirect or consequential loss.</p>

            <h3>Cap on Liability</h3>
            <p>DaizyAI&apos;s total aggregate liability shall not exceed the total fees paid by the Client in the <strong>12 months preceding the event giving rise to the claim</strong>.</p>

            <h3>Exceptions</h3>
            <p>Nothing in these Terms limits or excludes liability for death or personal injury caused by negligence, fraud, or any liability that cannot be limited by law.</p>

            <h3>Client&apos;s Indemnity</h3>
            <p>The Client shall indemnify DaizyAI against any claim arising from the Client&apos;s breach of these Terms, failure to comply with applicable law, or any third-party claim arising from the content of scripts or information provided during onboarding.</p>
          </div>

          {/* 13 */}
          <div className="legal-section" id="t13">
            <p className="legal-section-num">13</p>
            <h2>Term &amp; Termination</h2>

            <h3>Term</h3>
            <p>This Agreement commences on the date the Client signs an Order Form or pays the first invoice, and continues on a monthly rolling basis.</p>

            <h3>Cancellation by the Client</h3>
            <p>The Client may cancel with <strong>30 days&apos; written notice</strong> to <a href="mailto:daizyaiinfo@gmail.com">daizyaiinfo@gmail.com</a>. No refund is given for the current billing month.</p>

            <h3>Termination by DaizyAI</h3>
            <ul>
              <li>Immediately, on written notice, for Acceptable Use breaches or incurable material breach</li>
              <li>On 14 days&apos; written notice for unpaid invoices</li>
              <li>On 30 days&apos; written notice for any reason (with pro-rata refund of prepaid fees)</li>
            </ul>

            <h3>Effect of Termination</h3>
            <ul>
              <li>The Agent will be deactivated and the Client&apos;s licence will end</li>
              <li>DaizyAI will delete all caller data within 30 days</li>
              <li>Each party will return or destroy the other&apos;s Confidential Information</li>
              <li>All outstanding fees become immediately due and payable</li>
              <li>Sections that by nature should survive termination will survive</li>
            </ul>
          </div>

          {/* 14 */}
          <div className="legal-section" id="t14">
            <p className="legal-section-num">14</p>
            <h2>Data Protection</h2>
            <p>The parties&apos; data protection obligations are governed by the <strong>Data Processing Agreement (DPA)</strong> which forms part of this Agreement.</p>
            <p>Key points:</p>
            <ul>
              <li>DaizyAI processes personal data relating to the Client&apos;s callers as Data Processor</li>
              <li>The Client is the Data Controller and is responsible for having a lawful basis</li>
              <li>DaizyAI will assist the Client in meeting their UK GDPR obligations</li>
              <li>DaizyAI will notify the Client within 48 hours of becoming aware of a personal data breach</li>
              <li>DaizyAI will not sub-process caller data except as disclosed in the Privacy Policy</li>
            </ul>
          </div>

          {/* 15 */}
          <div className="legal-section" id="t15">
            <p className="legal-section-num">15</p>
            <h2>General</h2>

            <h3>Entire Agreement</h3>
            <p>These Terms, together with any signed Order Form and the DPA, constitute the entire agreement between the parties.</p>

            <h3>Variation</h3>
            <p>DaizyAI may update these Terms from time to time. Clients will be notified by email at least 30 days before material changes take effect.</p>

            <h3>Assignment</h3>
            <p>The Client may not assign this Agreement without DaizyAI&apos;s prior written consent. DaizyAI may assign to a successor entity with 30 days&apos; notice.</p>

            <h3>Waiver</h3>
            <p>A failure or delay to exercise any right does not constitute a waiver.</p>

            <h3>Severability</h3>
            <p>If any provision is found to be unlawful or unenforceable, it will be deemed severable.</p>

            <h3>Force Majeure</h3>
            <p>Neither party shall be liable for any failure or delay resulting from circumstances beyond their reasonable control.</p>

            <h3>Third-Party Rights</h3>
            <p>Nothing in these Terms confers any benefit on any person who is not a party to this Agreement.</p>

            <h3>Governing Law &amp; Jurisdiction</h3>
            <p>These Terms are governed by the laws of <strong>England and Wales</strong>. Each party submits to the exclusive jurisdiction of the courts of England and Wales.</p>

            <h3>Notices</h3>
            <p>Notices under this Agreement may be given by email. Notices to DaizyAI should be sent to <a href="mailto:daizyaiinfo@gmail.com">daizyaiinfo@gmail.com</a>.</p>

            <div className="legal-contact-box">
              <p><strong>DaizyAI Ltd</strong></p>
              <p>Email: <a href="mailto:daizyaiinfo@gmail.com">daizyaiinfo@gmail.com</a></p>
              <p>Website: <a href="https://daizyai.uk">daizyai.uk</a></p>
            </div>
          </div>

        </div>
      </section>

      <Footer />
    </main>
  );
}
